# Docker-compose.yml - Punto-2

version: "3.8"
services:
  app-postgres-db:
    image: postgres:16-alpine
    hostname: app-postgres-db
    container_name: app-postgres-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      -  5455:5432
volumes:
  postgres-database:
    external: true
