# dockerfile populate-db - Punto-4

FROM python:3

WORKDIR /app

ADD requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY populate.py populate.py

CMD ["python", "populate.py"]


